name: leads_manager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 51.0.0+51

environment:
  sdk: ^3.4.0

dependency_overrides:
  package_info_plus: ^8.0.0
dependencies:
  app_links: ^6.3.1
  app_minimizer: ^1.0.0+3
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  bottom_bar_matu: ^1.4.0
  bottom_picker: ^2.3.3
  bubble: 1.2.1
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.5
  call_log: 4.0.0
  carousel_slider: 5.0.0
  chat_bubbles: ^1.4.0
  chatview: ^2.2.0
  chewie: ^1.8.5
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.2
  custom_searchable_dropdown: 2.1.1
  device_info_plus: ^11.0.0
  dio: 4.0.0
  dropdown_textfield: ^1.2.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  file_picker: ^5.2.9
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.0
  flutter_contacts: ^1.1.9+2
  flutter_debouncer: ^2.0.0
  flutter_dropdown: ^1.0.1+hotfix.1
  flutter_easyloading: 3.0.3
  flutter_foreground_task: ^8.7.0
  flutter_in_store_app_version_checker: ^1.7.1
  flutter_isolate: ^2.0.4
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_slidable: ^3.0.0
  flutter_svg: ^1.1.6
  flutter_typeahead: 4.8.0
  flutter_widget_from_html_core: ^0.15.1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^4.0.4
  http: ^1.2.2
  image_picker: ^0.8.2
  in_app_update: ^4.2.3
  internet_connection_checker: ^2.0.0
  intl: 0.19.0
  intl_phone_field: ^3.2.0
  keyboard_avoider: ^0.2.0
  load_switch: ^2.1.0
  loading_indicator: ^3.1.1
  logger: ^2.4.0
  markdown_toolbar: ^0.5.0
  motion_tab_bar: ^2.0.4
  mqtt_client: ^10.5.1
  multi_dropdown: ^1.0.2
  multi_select_flutter: 4.1.1
  omni_datetime_picker: ^2.0.4
  open_file: ^3.3.2
  path_provider: any
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  phone_state: ^1.0.4
  pinput: ^5.0.0
  record: ^5.0.5
  searchfield: ^1.0.1
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  simple_rich_text: 2.0.49
  simple_ripple_animation: ^0.0.9
  sms_autofill: ^2.4.0
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  super_tooltip: ^2.0.8
  syncfusion_flutter_charts: ^21.2.4
  table_calendar: ^3.0.8
  talker: ^4.3.2
  textfield_search: ^0.10.0
  universal_html: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^3.0.1
  vertical_card_pager: ^1.6.2
  video_player: ^2.9.2
  video_player_web: null
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.10.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/icon/
    - assets/sounds/sentSound.mp3
