// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZF1vxrfKzvISd84YZJbIR8vBvKLkqwc',
    appId: '1:854495007457:web:467c00983b018c73d71da0',
    messagingSenderId: '854495007457',
    projectId: 'leadsmanager-b1b49',
    authDomain: 'leadsmanager-b1b49.firebaseapp.com',
    storageBucket: 'leadsmanager-b1b49.appspot.com',
    measurementId: 'G-FZSFQ2Q28Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMEV2NeS9XocZaAZme35Dv8-AaMDNTlc',
    appId: '1:854495007457:android:b9b1e0e9e4723a17d71da0',
    messagingSenderId: '854495007457',
    projectId: 'leadsmanager-b1b49',
    storageBucket: 'leadsmanager-b1b49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjmJoLcs0sTXNSKNC5_PjKb600P4cTbU',
    appId: '1:854495007457:ios:db22d05e04c4d917d71da0',
    messagingSenderId: '854495007457',
    projectId: 'leadsmanager-b1b49',
    storageBucket: 'leadsmanager-b1b49.appspot.com',
    iosBundleId: 'com.example.leadManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjmJoLcs0sTXNSKNC5_PjKb600P4cTbU',
    appId: '1:854495007457:ios:db22d05e04c4d917d71da0',
    messagingSenderId: '854495007457',
    projectId: 'leadsmanager-b1b49',
    storageBucket: 'leadsmanager-b1b49.appspot.com',
    iosBundleId: 'com.example.leadManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ZF1vxrfKzvISd84YZJbIR8vBvKLkqwc',
    appId: '1:854495007457:web:9ccb3cdff25072d1d71da0',
    messagingSenderId: '854495007457',
    projectId: 'leadsmanager-b1b49',
    authDomain: 'leadsmanager-b1b49.firebaseapp.com',
    storageBucket: 'leadsmanager-b1b49.appspot.com',
    measurementId: 'G-YEJPDCYBS9',
  );
}
